# -*- coding: utf-8 -*-
"""chat_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bN4ywc7nh_w6TDALMzXOc2o3TXc0NiDl
"""

def menu():
        print ("======= Menu ========")
        print ("0 - Sair")
        print ("1 - Somar")
        print ("2 - Subtrair")
        print ("3 - Multiplicar")
        print ("4 - Dividir")
        opcao = int(input("Escolha uma opção:"))
        return opcao

op = menu()

print("Você escolheu:", op)

if op == 1:
    print("Você escolheu somar")
    num1 = int(input("Digite o primeiro número:"))
    num2 = int(input("Digite o segundo número:"))
    print("O resultado é:", num1 + num2)
elif op == 2:
    print("Você escolheu subtrair")
    num1 = int(input("Digite o primeiro número:"))
    num2 = int(input("Digite o segundo número:"))
    print("O resultado é:", num1 - num2)
elif op == 3:
    print("Você escolheu multiplicar")
    num1 = int(input("Digite o primeiro número:"))
    num2 = int(input("Digite o segundo número:"))
    print("O resultado é:", num1 * num2)
elif op == 4:
    print("Você escolheu dividir")
    num1 = int(input("Digite o primeiro número:"))
    num2 = int(input("Digite o segundo número:"))
    print("O resultado é:", num1 / num2)
elif op == 0:
    print("Você escolheu sair")
    exit()
else:
    print("Opção inválida")

from pymongo import MongoClient

conexao = MongoClient(
    "mongodb+srv://NicolasBD2:Nicolas123@cluster0.b2hh6pu.mongodb.net/",
    tls=True,
    tlsAllowInvalidCertificates=True
)
bd = conexao["consercar"]

clientes = bd["cliente"]

cliente_teste = {
    "cpf": "123.456.789-00",
    "nome": "Cliente Teste",
    "uf": "SP",
    "municipio": "São Paulo",
    "telefone": ["11999998888"],
    "endereco": {
        "rua": "Rua Teste",
        "numero": "123",
        "bairro": "Centro"
    },
    "email": ["teste@email.com"],
    "dataNas": "1990-01-01",
    "veiculo": ["Carro Exemplo"]
}

res = clientes.insert_one(cliente_teste)
print("Cliente cadastrado:", res.inserted_id)

from pymongo import MongoClient

# Conexão com o MongoDB
conexao = MongoClient(
    "mongodb+srv://barbaracarvalhosales1_db_user:yFw6d3uuv6lASbVc@consercar.3ra64cb.mongodb.net/?retryWrites=true&w=majority",
    tls=True,
    tlsAllowInvalidCertificates=True
)
bd = conexao.get_database("CONSERCAR")
colecao_notas = bd.get_collection("notafiscal")

# Nota de teste
nota_teste = {
    "numeroNota": 1,
    "descricaoServico": "Reparo de porta",
    "dataInicio": "2021-09-16T22:53:56",
    "dataFim": "2021-09-23T22:53:56",
    "valorTotal": 2388.69,
    "cnpjSeguradora": "04.718.936/0001-03",
    "cpfCliente": "123.456.789-00",  # CPF para teste
    "cnpjPrestadorServico": "90.157.462/0001-00",
    "dataEmissao": "2021-09-28T22:53:56"
}

# Inserir a nota no banco
resultado = colecao_notas.insert_one(nota_teste)
print(f"Nota inserida com ID: {resultado.inserted_id}")

# ======================
# BANCO DE DADOS
# ======================
conexao = MongoClient(
    "mongodb+srv://barbaracarvalhosales1_db_user:yFw6d3uuv6lASbVc@consercar.3ra64cb.mongodb.net/?retryWrites=true&w=majority",
    tls=True,
    tlsAllowInvalidCertificates=True
)

bd = conexao.get_database("CONSERCAR")
colecao = bd.get_collection("clientes")
colecao_servicos = bd.get_collection("servicos")
colecao_orcamento = bd.get_collection("orcamento")


# ======================
# CONTEXTO DE CONVERSA
# ======================
estado = {
    "acao": None,
    "dados": {}
}


# ======================
# FUNÇÃO PRINCIPAL
# ======================
def chat(mensagem, historico):

    global estado

    # -----------------------------
    # SE NÃO HÁ AÇÃO DEFINIDA AINDA
    # -----------------------------
    if estado["acao"] is None:

        opcoes = ["Cadastrar Cliente", "Consultar Cliente", "Orçamento", "Sair"]
        escolha, score = process.extractOne(mensagem, opcoes)

        if score < 60:
            return "❌ Não entendi. Você pode dizer:\n• cadastrar cliente\n• consultar cliente\n• orçamento\n• sair"

        estado["acao"] = escolha

        if escolha == "Cadastrar Cliente":
            return "✏️ Vamos cadastrar um cliente!\nQual é o *nome* do cliente?"

        elif escolha == "Consultar Cliente":
            return "🔍 Me diga o *nome do cliente* que você quer consultar."

        elif escolha == "Orçamento":
            return "🧾 Vamos fazer um orçamento!\nQual é o *nome do cliente*?"

        elif escolha == "Sair":
            estado["acao"] = None
            return "👋 Assistente encerrado."

    # ======================
    # CADASTRAR CLIENTE
    # ======================
    if estado["acao"] == "Cadastrar Cliente":

        # Se ainda não tem nome
        if "nome" not in estado["dados"]:
            estado["dados"]["nome"] = mensagem
            return "📱 Agora me informe o *telefone* do cliente."

        if "telefone" not in estado["dados"]:
            estado["dados"]["telefone"] = mensagem
            return "🏠 Agora preciso do *endereço*."

        if "endereco" not in estado["dados"]:
            estado["dados"]["endereco"] = mensagem

            colecao.insert_one(estado["dados"])
            nome = estado["dados"]["nome"]

            estado = {"acao": None, "dados": {}}
            return f"✅ Cliente **{nome}** cadastrado com sucesso!\n\nO que deseja fazer agora?"

    # ======================
    # CONSULTAR CLIENTE
    # ======================
    if estado["acao"] == "Consultar Cliente":

        nome_busca = mensagem
        cliente = colecao.find_one({"nome": {"$regex": nome_busca, "$options": "i"}})

        estado = {"acao": None, "dados": {}}

        if not cliente:
            return "❌ Nenhum cliente encontrado."

        return (
            f"### Cliente encontrado\n"
            f"**Nome:** {cliente.get('nome', '—')}\n"
            f"**Telefone:** {cliente.get('telefone', '—')}\n"
            f"**Endereço:** {cliente.get('endereco', '—')}\n\n"
            "O que deseja agora?"
        )

    # ======================
    # ORÇAMENTO
    # ======================
    if estado["acao"] == "Orçamento":

        if "cliente" not in estado["dados"]:
            estado["dados"]["cliente"] = mensagem
            return "🛠️ Qual é o *nome do serviço* para o orçamento?"

        if "servico" not in estado["dados"]:
            estado["dados"]["servico"] = mensagem

            cliente = colecao.find_one({"nome": {"$regex": estado["dados"]["cliente"], "$options": "i"}})
            servico = colecao_servicos.find_one({"servico": {"$regex": estado["dados"]["servico"], "$options": "i"}})

            estado_local = estado.copy()
            estado = {"acao": None, "dados": {}}

            if not cliente:
                return "❌ Cliente não encontrado."

            if not servico:
                return "❌ Serviço não encontrado."

            colecao_orcamento.insert_one({
                "cliente_id": cliente["_id"],
                "cliente_nome": cliente["nome"],
                "cliente_telefone": cliente.get("telefone"),
                "servico": servico["servico"],
                "valor": servico["valor"],
                "data": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            })

            return (
                f"### Orçamento gerado!\n"
                f"**Cliente:** {cliente['nome']}\n"
                f"**Serviço:** {servico['servico']}\n"
                f"**Valor:** R$ {servico['valor']:.2f}\n"
                f"**Telefone:** {cliente.get('telefone', '-')}\n\n"
                "O que deseja agora?"
            )


# ======================
# INTERFACE
# ======================
gr.ChatInterface(
    fn=chat,
    title="🤖 Assistente CONSERCAR",
    description="Chatbot para cadastro, consulta e orçamento."
).launch()

!pip install fuzzywuzzy
!pip install python-Levenshtein
!pip install pymongo
!pip install gradio

from pymongo import MongoClient
from fuzzywuzzy import process
from datetime import datetime
import gradio as gr

!pip install fuzzywuzzy
!pip install python-Levenshtein
!pip install pymongo
### imports
from pymongo import MongoClient
from fuzzywuzzy import process
from datetime import datetime

#!pip install fuzzywuzzy
#!pip install python-Levenshtein
#!pip install pymongo
### imports
#from pymongo import MongoClient
#from fuzzywuzzy import process
#from datetime import datetime
### conexao e coleções
conexao = MongoClient(
    "mongodb+srv://barbaracarvalhosales1_db_user:yFw6d3uuv6lASbVc@consercar.3ra64cb.mongodb.net/?retryWrites=true&w=majority",
    tls=True,
    tlsAllowInvalidCertificates=True
)

bd = conexao.get_database("CONSERCAR")
colecao = bd.get_collection("clientes")
colecao_servicos = bd.get_collection("servicos")
colecao_orcamento = bd.get_collection("orcamento")

# mini menu para repetir a opção ou sair sem voltar ao menu

def mini_menu_inteligente():
    opcoes = [
        "Repetir operação",
        "Voltar ao menu",
        "Sair"
    ]

    while True:
        print("\nO que deseja fazer agora?")
        print("- Repetir operação")
        print("- Voltar ao menu")
        print("- Sair")

        entrada = input("\nDigite sua escolha: ")
        escolha, score = process.extractOne(entrada, opcoes)

        if score < 60:
            print("Não entendi, tente novamente!")
            continue

        if escolha == "Repetir operação":
            return "repetir"

        elif escolha == "Voltar ao menu":
            return "menu"

        elif escolha == "Sair":
            return "sair"

# funções

def cadastrar_cliente():
    while True:
        nome = input("Nome do cliente: ")
        telefone = input("Telefone: ")
        endereco = input("Endereço: ")

        colecao.insert_one({
            "nome": nome,
            "telefone": telefone,
            "endereco": endereco
        })

        print("Cliente cadastrado com sucesso!")

        acao = mini_menu_inteligente()
        if acao == "repetir":
            continue
        elif acao == "menu":
            return None
        elif acao == "sair":
            return "sair"

#
def consultar_cliente():
    while True:
        nome = input("Digite o nome do cliente: ")

        cliente = colecao.find_one({"nome": {"$regex": nome, "$options": "i"}})

        if cliente:
            print("\n--- Cliente encontrado ---")
            print(f"Nome: {cliente.get('nome', 'Não informado')}")
            print(f"Telefone: {cliente.get('telefone', 'Não informado')}")
            print(f"Endereço: {cliente.get('endereco', 'Não informado')}")
        else:
            print("Nenhum cliente encontrado.")

        acao = mini_menu_inteligente()
        if acao == "repetir":
            continue
        elif acao == "menu":
            return None
        elif acao == "sair":
            return "sair"

#
def orcamento():
    while True:
        nome_cliente = input("Nome do cliente: ")
        cliente = colecao.find_one({"nome": {"$regex": nome_cliente, "$options": "i"}})

        if not cliente:
            print("Cliente não encontrado!")
            acao = mini_menu_inteligente()
            if acao == "repetir":
                continue
            elif acao == "menu":
                return None
            elif acao == "sair":
                return "sair"

        servicos = list(colecao_servicos.find({}))

        if not servicos:
            print("Nenhum serviço cadastrado.")
            acao = mini_menu_inteligente()
            if acao == "repetir":
                continue
            elif acao == "menu":
                return None
            elif acao == "sair":
                return "sair"

        print("\n====== TABELA DE SERVIÇOS ======")
        for i, s in enumerate(servicos, start=1):
            print(f"{i}. {s['servico']} - R$ {s['valor']:.2f}")

        try:
            op = int(input("\nEscolha o serviço (número): "))
            if op < 1 or op > len(servicos):
                print("Opção inválida!")
                continue
        except ValueError:
            print("Digite um número válido!")
            continue

        servico = servicos[op - 1]

        colecao_orcamento.insert_one({
            "cliente_id": cliente["_id"],
            "cliente_nome": cliente["nome"],
            "servico": servico["servico"],
            "cliente_telefone":cliente ["telefone"],
            "valor": servico["valor"],
            "data": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        })

        print("\nOrçamento registrado com sucesso!")

        acao = mini_menu_inteligente()
        if acao == "repetir":
            continue
        elif acao == "menu":
            return None
        elif acao == "sair":
            return "sair"

#
def menu():

    lista_opcoes = [
        "Cadastrar Cliente",
        "Consultar Cliente",
        "Orçamento",
        "Sair"
    ]

    while True:
        print("\n====== ASSISTENTE CONSERCAR ======")
        print("Opções disponíveis:")
        for op in lista_opcoes:
            print(f"- {op}")

        entrada = input("\nComo posso ajudar? ")

        escolha, porcentagem = process.extractOne(entrada, lista_opcoes)

        if porcentagem < 60:
            print("Não entendi! Tente novamente\n")
            continue

        print(f"Você escolheu: {escolha}")


        if escolha == "Cadastrar Cliente":
            resultado = cadastrar_cliente()
            if resultado == "sair":
                print("Encerrando o assistente.")
                break

        elif escolha == "Consultar Cliente":
            resultado = consultar_cliente()
            if resultado == "sair":
                print("Encerrando o assistente.")
                break

        elif escolha == "Orçamento":
            resultado = orcamento()
            if resultado == "sair":
                print("Encerrando o assistente.")
                break

        elif escolha == "Sair":
            print("Encerrando o assistente. ")
            break

# executando menu principal
menu()

# ===============================
#   IMPORTS E CONEXÃO
# ===============================
from pymongo import MongoClient
from fuzzywuzzy import process
from datetime import datetime

# ========= SAFE INPUT ==========
def safe_input(texto):
    try:
        return input(texto)
    except EOFError:
        print("\n⚠ Nenhuma entrada recebida (EOF). Retornando vazio.")
        return ""

# ===============================
#   CONEXÃO
# ===============================
conexao = MongoClient(
    "mongodb+srv://barbaracarvalhosales1_db_user:yFw6d3uuv6lASbVc@consercar.3ra64cb.mongodb.net/?retryWrites=true&w=majority",
    tls=True,
    tlsAllowInvalidCertificates=True
)

bd = conexao.get_database("CONSERCAR")
colecao_orcamento = bd.get_collection("notafiscal")  # sua coleção usada para status


# ===============================
#     FUNÇÃO STATUS DO SERVIÇO
# ===============================
def verificar_status():
    while True:
        cpf = safe_input("\nDigite o CPF para consultar o serviço: ")

        nota = colecao_orcamento.find_one({"cpfCliente": cpf})

        if not nota:
            print("\n❌ Nenhum serviço encontrado para esse CPF.")
        else:
            data_inicio = nota.get("dataInicio")
            data_fim = nota.get("dataFim")

            if not data_inicio and not data_fim:
                status = "🔵 EM ANÁLISE"
            elif data_inicio and not data_fim:
                status = "🟠 EM ANDAMENTO"
            else:
                status = "🟢 FINALIZADO"

            print("\n=== STATUS DO SERVIÇO ===")
            print(f"Cliente: {nota.get('cpfCliente')}")
            print(f"Serviço: {nota.get('descricaoServico')}")
            print(f"Status: {status}")
            print("==========================")

        acao = mini_menu_inteligente()
        if acao == "repetir":
            continue
        elif acao == "menu":
            return
        elif acao == "sair":
            return "sair"


# ===============================
#   FUNÇÃO ORÇAMENTO SIMPLES
# ===============================
def fazer_orcamento():
    print("\nPara fazer orçamento, entre em contato com nosso atendente 🙂")
    print("📞 WhatsApp: 11 94794-6318")
    print("📧 Email: uilsonfoliveira@hotmail.com")

    acao = mini_menu_inteligente()
    if acao == "menu":
        return
    elif acao == "sair":
        return "sair"


# ===============================
#   FUNÇÃO ATENDENTE
# ===============================
def falar_atendente():
    print("\n📞 Você pode falar com um atendente pelos canais abaixo:\n")
    print("WhatsApp: 11 94794-6318")
    print("Telefone fixo: 5677-3582")
    print("Email: uilsonfoliveira@hotmail.com")

    acao = mini_menu_inteligente()
    if acao == "menu":
        return
    elif acao == "sair":
        return "sair"


# ===============================
#   FUNÇÃO INFORMAÇÕES DA LOJA
# ===============================
def informacoes_loja():
    print("\n🏪 INFORMAÇÕES DA CONSERCAR")
    print("Horário: 07:30 às 18:00")
    print("Endereço: (editar depois)")
    print("WhatsApp: 11 94794-6318")
    print("Telefone fixo: 5677-3582")

    acao = mini_menu_inteligente()
    if acao == "menu":
        return
    elif acao == "sair":
        return "sair"


# ===============================
#    MINI MENU INTELIGENTE
# ===============================
def mini_menu_inteligente():
    opcoes = ["Repetir operação", "Voltar ao menu", "Sair"]

    while True:
        print("\nO que deseja fazer agora?")
        print("- Repetir operação")
        print("- Voltar ao menu")
        print("- Sair")

        entrada = safe_input("\nDigite sua escolha: ")
        escolha, score = process.extractOne(entrada, opcoes)

        if score < 60:
            print("Não entendi, tente novamente!")
            continue

        if escolha == "Repetir operação":
            return "repetir"
        elif escolha == "Voltar ao menu":
            return "menu"
        else:
            return "sair"


# ===============================
#   MENU PRINCIPAL CLIENTE FINAL
# ===============================
def menu():
    opcoes = [
        "Fazer Orçamento",
        "Consultar Status do Serviço",
        "Falar com Atendente",
        "Informações da Loja",
        "Sair"
    ]

    print("\n====== ASSISTENTE CONSERCAR ======")

    while True:
        print("\n📌 Como posso ajudar hoje?")
        for op in opcoes:
            print(f"- {op}")

        entrada = safe_input("\nDigite sua escolha: ")

        escolha, score = process.extractOne(entrada, opcoes)

        if score < 60:
            print("Não entendi sua escolha, tente novamente.\n")
            continue

        print(f"\n➡️ Você escolheu: {escolha}\n")

        if escolha == "Fazer Orçamento":
            if fazer_orcamento() == "sair":
                break

        elif escolha == "Consultar Status do Serviço":
            if verificar_status() == "sair":
                break

        elif escolha == "Falar com Atendente":
            if falar_atendente() == "sair":
                break

        elif escolha == "Informações da Loja":
            if informacoes_loja() == "sair":
                break

        elif escolha == "Sair":
            print("Obrigada por usar o assistente 💛")
            break


# ===============================
#        EXECUTAR MENU
# ===============================
menu()

!pip install fuzzywuzzy
!pip install python-Levenshtein
!pip install pymongo
from pymongo import MongoClient
from fuzzywuzzy import process
conexao = MongoClient(
    "mongodb+srv://barbaracarvalhosales1_db_user:yFw6d3uuv6lASbVc@consercar.3ra64cb.mongodb.net/?retryWrites=true&w=majority",
    tls=True,
    tlsAllowInvalidCertificates=True
)